services:
  ollama:
    image: ollama/ollama:latest
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    restart: unless-stopped
    ports:
      - target: 11434
        published: "{{WEB_PORT}}"
        protocol: tcp
    volumes:
      - type: bind
        source: "{{VOLUME_OLLAMA__ROOT__OLLAMA}}"
        target: /root/.ollama
