services:
  rdtclient:
    environment:
      PGID: "{{PGID}}"
      PUID: "{{PUID}}"
      TZ: "{{TZ}}"
      UMASK: "002"
    cpu_shares: 50
    command: []
    deploy:
      resources:
        reservations:
          memory: 64M
    image: rogerfar/rdtclient:latest
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/RDTClient/icon.png
    ports:
      - target: 6500
        published: "{{WEB_PORT}}"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: "{{VOLUME_RDTCLIENT__DATA_DOWNLOADS}}"
        target: /data/downloads
      - type: bind
        source: "{{VOLUME_RDTCLIENT__DATA_DB}}"
        target: /data/db
    network_mode: bridge
    privileged: false
