services:
  librechat-api:
    ports:
      - "{{WEB_PORT}}:3080"
    depends_on:
      - librechat-mongodb
      - librechat-rag-api
    image: ghcr.io/danny-avila/librechat-dev:latest
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - ASSISTANTS_API_KEY=user_provided
      - OPENAI_API_KEY=user_provided
      - GOOGLE_KEY=user_provided
      - ANTHROPIC_API_KEY=user_provided
      - HOST=0.0.0.0
      - PORT=3080
      - DOMAIN_CLIENT=http://0.0.0.0:3080
      - DOMAIN_SERVER=http://0.0.0.0:3080
      - NO_INDEX=true
      - TRUST_PROXY=1
      - CONSOLE_JSON=false
      - DEBUG_LOGGING=true
      - DEBUG_CONSOLE=false
      - MONGO_URI=mongodb://librechat-mongodb:27017/LibreChat
      - MEILI_HOST=http://librechat-meilisearch:7700
      - RAG_PORT=8000
      - RAG_API_URL=http://librechat-rag-api:8000
      - SEARCH=true
      - MEILI_NO_ANALYTICS=true
      - OPENAI_MODERATION=false
      - BAN_VIOLATIONS=true
      - BAN_DURATION=1000 * 60 * 60 * 2
      - BAN_INTERVAL=20
      - LOGIN_VIOLATION_SCORE=1
      - REGISTRATION_VIOLATION_SCORE=1
      - CONCURRENT_VIOLATION_SCORE=1
      - MESSAGE_VIOLATION_SCORE=1
      - NON_BROWSER_VIOLATION_SCORE=20
      - TTS_VIOLATION_SCORE=0
      - STT_VIOLATION_SCORE=0
      - FORK_VIOLATION_SCORE=0
      - IMPORT_VIOLATION_SCORE=0
      - FILE_UPLOAD_VIOLATION_SCORE=0
      - LOGIN_MAX=7
      - LOGIN_WINDOW=5
      - REGISTER_MAX=5
      - REGISTER_WINDOW=60
      - LIMIT_CONCURRENT_MESSAGES=true
      - CONCURRENT_MESSAGE_MAX=2
      - LIMIT_MESSAGE_IP=true
      - MESSAGE_IP_MAX=40
      - MESSAGE_IP_WINDOW=1
      - LIMIT_MESSAGE_USER=false
      - MESSAGE_USER_MAX=40
      - MESSAGE_USER_WINDOW=1
      - ILLEGAL_MODEL_REQ_SCORE=5
      - ALLOW_EMAIL_LOGIN=true
      - ALLOW_REGISTRATION=true
      - ALLOW_SOCIAL_LOGIN=false
      - ALLOW_SOCIAL_REGISTRATION=false
      - ALLOW_PASSWORD_RESET=false
      - ALLOW_UNVERIFIED_EMAIL_LOGIN=true
      - SESSION_EXPIRY=1000 * 60 * 15
      - REFRESH_TOKEN_EXPIRY=(1000 * 60 * 60 * 24) * 7
      - JWT_SECRET=16f8c0ef4a5d391b26034086c628469d3f9f497f08163ab9b40137092f2909ef
      - JWT_REFRESH_SECRET=eaa5191f2914e30b9387fd84e254e4ba6fc51b4654968a9b0803b456a54b8418
      - CREDS_KEY=f34be427ebb29de8d88c107a71546019685ed8b241d8f2ed00c3df97ad2566f0
      - CREDS_IV=e2341419ec3dd3d19b13a1a87fafcbfb
      - DEBUG_PLUGINS=true
      - DEBUG_OPENAI=false
    volumes:
      - type: bind
        source: "{{VOLUME_LIBRECHAT_API__APP_CLIENT_PUBLIC_IMAGES}}"
        target: /app/client/public/images
      - type: bind
        source: "{{VOLUME_LIBRECHAT_API__APP_UPLOADS}}"
        target: /app/uploads
      - type: bind
        source: "{{VOLUME_LIBRECHAT_API__APP_API_LOGS}}"
        target: /app/api/logs
    networks:
      - librechat-net
    deploy:
      resources:
        reservations:
          memory: 1024M
  librechat-mongodb:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - type: bind
        source: "{{VOLUME_LIBRECHAT_MONGODB__DATA_DB}}"
        target: /data/db
    command:
      - mongod
      - --noauth
    networks:
      - librechat-net
    deploy:
      resources:
        reservations:
          memory: 1024M
  librechat-meilisearch:
    image: getmeili/meilisearch:latest
    restart: unless-stopped
    user: 1000:1000
    environment:
      - MEILI_HOST=http://librechat-meilisearch:7700
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=DrhYf7zENyR6AlUCKmnz0eYASOQdl6zxH7s7MKFSfFCt
    volumes:
      - type: bind
        source: "{{VOLUME_LIBRECHAT_MEILISEARCH__MEILI_DATA}}"
        target: /meili_data
    networks:
      - librechat-net
  librechat-vectordb:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    restart: unless-stopped
    volumes:
      - "{{VOLUME_LIBRECHAT_VECTORDB__VAR_LIB_POSTGRESQL_DATA}}:/var/lib/postgr\
        esql/data"
    networks:
      - librechat-net
    deploy:
      resources:
        reservations:
          memory: 500M
  librechat-rag-api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    environment:
      - DB_HOST=librechat-vectordb
      - RAG_PORT=8000
    restart: unless-stopped
    depends_on:
      - librechat-vectordb
    networks:
      - librechat-net
    deploy:
      resources:
        reservations:
          memory: 1024M
networks:
  librechat-net:
    driver: bridge
