services:
  convertx:
    image: c4illin/convertx:latest
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          memory: 500M
    ports:
      - "{{WEB_PORT}}:3000"
    environment:
      - JWT_SECRET={{JWT_SECRET}}
      - HTTP_ALLOWED=true
    volumes:
      - type: bind
        source: "{{VOLUME_CONVERTX__APP_DATA}}"
        target: /app/data
    network_mode: bridge
