/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as FilesRouteImport } from './routes/files'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppsIndexRouteImport } from './routes/apps/index'
import { Route as StorageMountIdRouteImport } from './routes/storage.$mountId'
import { Route as AppsNewRouteImport } from './routes/apps/new'
import { Route as AppsAppIdRouteImport } from './routes/apps/$appId'
import { Route as AppsTemplatesIndexRouteImport } from './routes/apps/templates/index'
import { Route as AppsTemplatesTemplateIdRouteImport } from './routes/apps/templates/$templateId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesRoute = FilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageMountIdRoute = StorageMountIdRouteImport.update({
  id: '/storage/$mountId',
  path: '/storage/$mountId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsNewRoute = AppsNewRouteImport.update({
  id: '/apps/new',
  path: '/apps/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsAppIdRoute = AppsAppIdRouteImport.update({
  id: '/apps/$appId',
  path: '/apps/$appId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsTemplatesIndexRoute = AppsTemplatesIndexRouteImport.update({
  id: '/apps/templates/',
  path: '/apps/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsTemplatesTemplateIdRoute = AppsTemplatesTemplateIdRouteImport.update({
  id: '/apps/templates/$templateId',
  path: '/apps/templates/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/files': typeof FilesRoute
  '/settings': typeof SettingsRoute
  '/apps/$appId': typeof AppsAppIdRoute
  '/apps/new': typeof AppsNewRoute
  '/storage/$mountId': typeof StorageMountIdRoute
  '/apps/': typeof AppsIndexRoute
  '/apps/templates/$templateId': typeof AppsTemplatesTemplateIdRoute
  '/apps/templates/': typeof AppsTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/files': typeof FilesRoute
  '/settings': typeof SettingsRoute
  '/apps/$appId': typeof AppsAppIdRoute
  '/apps/new': typeof AppsNewRoute
  '/storage/$mountId': typeof StorageMountIdRoute
  '/apps': typeof AppsIndexRoute
  '/apps/templates/$templateId': typeof AppsTemplatesTemplateIdRoute
  '/apps/templates': typeof AppsTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/files': typeof FilesRoute
  '/settings': typeof SettingsRoute
  '/apps/$appId': typeof AppsAppIdRoute
  '/apps/new': typeof AppsNewRoute
  '/storage/$mountId': typeof StorageMountIdRoute
  '/apps/': typeof AppsIndexRoute
  '/apps/templates/$templateId': typeof AppsTemplatesTemplateIdRoute
  '/apps/templates/': typeof AppsTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/files'
    | '/settings'
    | '/apps/$appId'
    | '/apps/new'
    | '/storage/$mountId'
    | '/apps/'
    | '/apps/templates/$templateId'
    | '/apps/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/files'
    | '/settings'
    | '/apps/$appId'
    | '/apps/new'
    | '/storage/$mountId'
    | '/apps'
    | '/apps/templates/$templateId'
    | '/apps/templates'
  id:
    | '__root__'
    | '/'
    | '/files'
    | '/settings'
    | '/apps/$appId'
    | '/apps/new'
    | '/storage/$mountId'
    | '/apps/'
    | '/apps/templates/$templateId'
    | '/apps/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FilesRoute: typeof FilesRoute
  SettingsRoute: typeof SettingsRoute
  AppsAppIdRoute: typeof AppsAppIdRoute
  AppsNewRoute: typeof AppsNewRoute
  StorageMountIdRoute: typeof StorageMountIdRoute
  AppsIndexRoute: typeof AppsIndexRoute
  AppsTemplatesTemplateIdRoute: typeof AppsTemplatesTemplateIdRoute
  AppsTemplatesIndexRoute: typeof AppsTemplatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files': {
      id: '/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/': {
      id: '/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage/$mountId': {
      id: '/storage/$mountId'
      path: '/storage/$mountId'
      fullPath: '/storage/$mountId'
      preLoaderRoute: typeof StorageMountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/new': {
      id: '/apps/new'
      path: '/apps/new'
      fullPath: '/apps/new'
      preLoaderRoute: typeof AppsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$appId': {
      id: '/apps/$appId'
      path: '/apps/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof AppsAppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/templates/': {
      id: '/apps/templates/'
      path: '/apps/templates'
      fullPath: '/apps/templates/'
      preLoaderRoute: typeof AppsTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/templates/$templateId': {
      id: '/apps/templates/$templateId'
      path: '/apps/templates/$templateId'
      fullPath: '/apps/templates/$templateId'
      preLoaderRoute: typeof AppsTemplatesTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FilesRoute: FilesRoute,
  SettingsRoute: SettingsRoute,
  AppsAppIdRoute: AppsAppIdRoute,
  AppsNewRoute: AppsNewRoute,
  StorageMountIdRoute: StorageMountIdRoute,
  AppsIndexRoute: AppsIndexRoute,
  AppsTemplatesTemplateIdRoute: AppsTemplatesTemplateIdRoute,
  AppsTemplatesIndexRoute: AppsTemplatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
