services:
  docmost:
    image: docmost/docmost:latest
    deploy:
      resources:
        reservations:
          memory: 512M
    restart: unless-stopped
    ports:
      - target: 3000
        published: "{{WEB_PORT}}"
        protocol: tcp
    volumes:
      - type: bind
        source: "{{VOLUME_DOCMOST__APP_DATA_STORAGE}}"
        target: /app/data/storage
    environment:
      APP_URL: http://localhost:3000
      APP_SECRET: {{APP_SECRET}}
      DATABASE_URL: postgresql://docmost:{{POSTGRES_PASSWORD}}@docmost-db:5432/docmost?schema=public
      REDIS_URL: redis://docmost-redis:6379
    networks:
      - docmost-network
    depends_on:
      - docmost-db
      - docmost-redis
  docmost-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: {{POSTGRES_PASSWORD}}
    restart: unless-stopped
    volumes:
      - type: bind
        source: "{{VOLUME_DOCMOST_DB__VAR_LIB_POSTGRESQL_DATA}}"
        target: /var/lib/postgresql/data
    networks:
      - docmost-network
  docmost-redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - type: bind
        source: "{{VOLUME_DOCMOST_REDIS__DATA}}"
        target: /data
    networks:
      - docmost-network
networks:
  docmost-network:
    driver: bridge
