services:
  ombi:
    environment:
      BASE_URL: /ombi
      PGID: "1000"
      PUID: "1000"
      TZ: Europe/London
    image: linuxserver/ombi:latest
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 3579
        published: "{{WEB_PORT}}"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: "{{VOLUME_OMBI__CONFIG}}"
        target: /config
