services:
  retroarch:
    image: inglebard/retroarch-web:latest
    deploy:
      resources:
        reservations:
          memory: 64M
    restart: unless-stopped
    environment:
      - ROOT_WWW_PATH="/var/www/html"
    ports:
      - "{{WEB_PORT}}:80"
