services:
  app:
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    cpu_shares: 90
    deploy:
      resources:
        limits:
          memory: 1794M
    image: netdata/netdata:latest
    labels:
      icon: https://icon.casaos.io/main/all/netdata.png
    pid: host
    ports:
      - target: 19999
        published: "{{WEB_PORT}}"
        protocol: tcp
    restart: unless-stopped
    security_opt:
      - apparmor:unconfined
    volumes:
      - type: bind
        source: "{{VOLUME_APP__ETC_NETDATA}}"
        target: /etc/netdata
      - type: bind
        source: "{{VOLUME_APP__VAR_LIB_NETDATA}}"
        target: /var/lib/netdata
      - type: bind
        source: "{{VOLUME_APP__VAR_CACHE_NETDATA}}"
        target: /var/cache/netdata
      - type: bind
        source: "{{VOLUME_APP__HOST_ETC_PASSWD}}"
        target: /host/etc/passwd
      - type: bind
        source: "{{VOLUME_APP__HOST_ETC_GROUP}}"
        target: /host/etc/group
      - type: bind
        source: "{{VOLUME_APP__HOST_PROC}}"
        target: /host/proc
      - type: bind
        source: "{{VOLUME_APP__HOST_SYS}}"
        target: /host/sys
      - type: bind
        source: "{{VOLUME_APP__HOST_ETC_OS_RELEASE}}"
        target: /host/etc/os-release
      - type: bind
        source: "{{VOLUME_APP__VAR_RUN_DOCKER_SOCK}}"
        target: /var/run/docker.sock
    network_mode: bridge
    privileged: false
