services:
  tautulli:
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Europe/London
    image: linuxserver/tautulli:latest
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 8181
        published: "{{WEB_PORT}}"
    restart: unless-stopped
    volumes:
      - type: bind
        source: "{{VOLUME_TAUTULLI__CONFIG}}"
        target: /config
