services:
  smokeping:
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: Europe/London
    image: linuxserver/smokeping:latest
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 80
        published: "{{WEB_PORT}}"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: "{{VOLUME_SMOKEPING__CONFIG}}"
        target: /config
      - type: bind
        source: "{{VOLUME_SMOKEPING__DATA}}"
        target: /data
