services:
  vaultwarden:
    image: vaultwarden/server:latest
    deploy:
      resources:
        reservations:
          memory: 256M
    network_mode: bridge
    ports:
      - target: 80
        published: "{{WEB_PORT}}"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: "{{VOLUME_VAULTWARDEN__DATA}}"
        target: /data
